export const USER_NOT_FOLLOW = "notFollowedUsers"
export const POST_BY_FOLLOW = "POST_BY_FOLLOW"
export const POST_BY_EXPLORE = "POST_BY_EXPLORE"
export const POST_BY_SELF = "POST_BY_SELF"
export const POST_BY_REEL = "POST_BY_REEL"